// auto generated by KTagNo-gen.php
package com.kujirahand.KPage;
import java.util.HashMap;
/**
 * define tag no
 */
public class KTagNo {
//---
    // # meta elements
    final public static int UNKNOWN = 0x0;
    final public static int TEXT = 0x1;
    final public static int HTML = 0x2;
    final public static int HEAD = 0x3;
    final public static int BODY = 0x4;
    final public static int TITLE = 0x5;
    final public static int LINK = 0x6;
    final public static int META = 0x7;
    final public static int STYLE = 0x8;
    final public static int SCRIPT = 0x9;
    // # paragraph
    final public static int DIV = 0x10;
    final public static int P = 0x11;
    final public static int UL = 0x12;
    final public static int OL = 0x13;
    final public static int FIGURE = 0x14;
    final public static int H1 = 0x15;
    final public static int H2 = 0x16;
    final public static int H3 = 0x17;
    final public static int H4 = 0x18;
    final public static int H5 = 0x19;
    final public static int H6 = 0x1a;
    // # line
    final public static int BR = 0x20;
    final public static int LI = 0x21;
    final public static int HR = 0x22;
    final public static int TR = 0x23;
    final public static int FIGCAPTION = 0x24;
    final public static int CAPTION = 0x25;
    // # font
    final public static int STRONG = 0x30;
    final public static int B = 0x31;
    final public static int U = 0x32;
    final public static int SUP = 0x33;
    final public static int SPAN = 0x34;
    final public static int EM = 0x35;
    final public static int TH = 0x36;
    // # image link
    final public static int IMG = 0x40;
    final public static int A = 0x41;
    // # system use
    final public static int USER_MARKER = 0x60;
    final public static int DRAW_IMAGE = 0x61;
    // # unsupport tag
    final public static int CENTER = 0xa0;
    final public static int TABLE = 0xa1;
    final public static int TD = 0xa2;
    final public static int CODE = 0xa3;
    final public static int FONT = 0xa4;
    final public static int ASIDE = 0xa5;
    final public static int ARTICLE = 0xa6;
    final public static int BASE = 0xa7;
    final public static int NOSCRIPT = 0xa8;
    final public static int SECTION = 0xa9;
    final public static int NAV = 0xaa;
    final public static int HGROUP = 0xab;
    final public static int FOOTER = 0xac;
    final public static int ADDRESS = 0xad;
    final public static int BLOCKQUOTE = 0xae;
    final public static int DT = 0xaf;
    final public static int DL = 0xb0;
    final public static int DD = 0xb1;
    final public static int MAIN = 0xb2;
    final public static int SMALL = 0xb3;
    final public static int S = 0xb4;
    final public static int CITE = 0xb5;
    final public static int Q = 0xb6;
    final public static int DFN = 0xb7;
    final public static int ABBR = 0xb8;
    final public static int TIME = 0xb9;
    final public static int VAR = 0xba;
    final public static int SAMP = 0xbb;
    final public static int KBD = 0xbc;
    final public static int SUB = 0xbd;
    final public static int I = 0xbe;
    final public static int MARK = 0xbf;
    final public static int RUBY = 0xc0;
    final public static int RT = 0xc1;
    final public static int RP = 0xc2;
    final public static int RB = 0xc3;
    final public static int BDO = 0xc4;
    final public static int WBR = 0xc5;
    final public static int INS = 0xc6;
    final public static int DEL = 0xc7;
    final public static int IFRAME = 0xc8;
    final public static int EMBED = 0xc9;
    final public static int OBJECT = 0xca;
    final public static int PARAM = 0xcb;
    final public static int VIDEO = 0xcc;
    final public static int AUDIO = 0xcd;
    final public static int SOURCES = 0xce;
    final public static int CANVAS = 0xcf;
    final public static int MAP = 0xd0;
    final public static int AREA = 0xd1;
    final public static int HEADER = 0xd2;

    public static String toString(int no) {
        switch(no) {
        // # meta elements
        case 0x0 : return "unknown";
        case 0x1 : return "text";
        case 0x2 : return "html";
        case 0x3 : return "head";
        case 0x4 : return "body";
        case 0x5 : return "title";
        case 0x6 : return "link";
        case 0x7 : return "meta";
        case 0x8 : return "style";
        case 0x9 : return "script";
        // # paragraph
        case 0x10 : return "div";
        case 0x11 : return "p";
        case 0x12 : return "ul";
        case 0x13 : return "ol";
        case 0x14 : return "figure";
        case 0x15 : return "h1";
        case 0x16 : return "h2";
        case 0x17 : return "h3";
        case 0x18 : return "h4";
        case 0x19 : return "h5";
        case 0x1a : return "h6";
        // # line
        case 0x20 : return "br";
        case 0x21 : return "li";
        case 0x22 : return "hr";
        case 0x23 : return "tr";
        case 0x24 : return "figcaption";
        case 0x25 : return "caption";
        // # font
        case 0x30 : return "strong";
        case 0x31 : return "b";
        case 0x32 : return "u";
        case 0x33 : return "sup";
        case 0x34 : return "span";
        case 0x35 : return "em";
        case 0x36 : return "th";
        // # image link
        case 0x40 : return "img";
        case 0x41 : return "a";
        // # system use
        case 0x60 : return "user:marker";
        case 0x61 : return "draw:image";
        // # unsupport tag
        case 0xa0 : return "center";
        case 0xa1 : return "table";
        case 0xa2 : return "td";
        case 0xa3 : return "code";
        case 0xa4 : return "font";
        case 0xa5 : return "aside";
        case 0xa6 : return "article";
        case 0xa7 : return "base";
        case 0xa8 : return "noscript";
        case 0xa9 : return "section";
        case 0xaa : return "nav";
        case 0xab : return "hgroup";
        case 0xac : return "footer";
        case 0xad : return "address";
        case 0xae : return "blockquote";
        case 0xaf : return "dt";
        case 0xb0 : return "dl";
        case 0xb1 : return "dd";
        case 0xb2 : return "main";
        case 0xb3 : return "small";
        case 0xb4 : return "s";
        case 0xb5 : return "cite";
        case 0xb6 : return "q";
        case 0xb7 : return "dfn";
        case 0xb8 : return "abbr";
        case 0xb9 : return "time";
        case 0xba : return "var";
        case 0xbb : return "samp";
        case 0xbc : return "kbd";
        case 0xbd : return "sub";
        case 0xbe : return "i";
        case 0xbf : return "mark";
        case 0xc0 : return "ruby";
        case 0xc1 : return "rt";
        case 0xc2 : return "rp";
        case 0xc3 : return "rb";
        case 0xc4 : return "bdo";
        case 0xc5 : return "wbr";
        case 0xc6 : return "ins";
        case 0xc7 : return "del";
        case 0xc8 : return "iframe";
        case 0xc9 : return "embed";
        case 0xca : return "object";
        case 0xcb : return "param";
        case 0xcc : return "video";
        case 0xcd : return "audio";
        case 0xce : return "sources";
        case 0xcf : return "canvas";
        case 0xd0 : return "map";
        case 0xd1 : return "area";
        case 0xd2 : return "header";

        }
        return "unknown";
    }
    private static HashMap<String,Integer> tagMap = null;
    private static void genTagMap() {
        tagMap = new HashMap<String,Integer>();
        // # meta elements
        tagMap.put("unknown", 0x0);
        tagMap.put("text", 0x1);
        tagMap.put("html", 0x2);
        tagMap.put("head", 0x3);
        tagMap.put("body", 0x4);
        tagMap.put("title", 0x5);
        tagMap.put("link", 0x6);
        tagMap.put("meta", 0x7);
        tagMap.put("style", 0x8);
        tagMap.put("script", 0x9);
        // # paragraph
        tagMap.put("div", 0x10);
        tagMap.put("p", 0x11);
        tagMap.put("ul", 0x12);
        tagMap.put("ol", 0x13);
        tagMap.put("figure", 0x14);
        tagMap.put("h1", 0x15);
        tagMap.put("h2", 0x16);
        tagMap.put("h3", 0x17);
        tagMap.put("h4", 0x18);
        tagMap.put("h5", 0x19);
        tagMap.put("h6", 0x1a);
        // # line
        tagMap.put("br", 0x20);
        tagMap.put("li", 0x21);
        tagMap.put("hr", 0x22);
        tagMap.put("tr", 0x23);
        tagMap.put("figcaption", 0x24);
        tagMap.put("caption", 0x25);
        // # font
        tagMap.put("strong", 0x30);
        tagMap.put("b", 0x31);
        tagMap.put("u", 0x32);
        tagMap.put("sup", 0x33);
        tagMap.put("span", 0x34);
        tagMap.put("em", 0x35);
        tagMap.put("th", 0x36);
        // # image link
        tagMap.put("img", 0x40);
        tagMap.put("a", 0x41);
        // # system use
        tagMap.put("user:marker", 0x60);
        tagMap.put("draw:image", 0x61);
        // # unsupport tag
        tagMap.put("center", 0xa0);
        tagMap.put("table", 0xa1);
        tagMap.put("td", 0xa2);
        tagMap.put("code", 0xa3);
        tagMap.put("font", 0xa4);
        tagMap.put("aside", 0xa5);
        tagMap.put("article", 0xa6);
        tagMap.put("base", 0xa7);
        tagMap.put("noscript", 0xa8);
        tagMap.put("section", 0xa9);
        tagMap.put("nav", 0xaa);
        tagMap.put("hgroup", 0xab);
        tagMap.put("footer", 0xac);
        tagMap.put("address", 0xad);
        tagMap.put("blockquote", 0xae);
        tagMap.put("dt", 0xaf);
        tagMap.put("dl", 0xb0);
        tagMap.put("dd", 0xb1);
        tagMap.put("main", 0xb2);
        tagMap.put("small", 0xb3);
        tagMap.put("s", 0xb4);
        tagMap.put("cite", 0xb5);
        tagMap.put("q", 0xb6);
        tagMap.put("dfn", 0xb7);
        tagMap.put("abbr", 0xb8);
        tagMap.put("time", 0xb9);
        tagMap.put("var", 0xba);
        tagMap.put("samp", 0xbb);
        tagMap.put("kbd", 0xbc);
        tagMap.put("sub", 0xbd);
        tagMap.put("i", 0xbe);
        tagMap.put("mark", 0xbf);
        tagMap.put("ruby", 0xc0);
        tagMap.put("rt", 0xc1);
        tagMap.put("rp", 0xc2);
        tagMap.put("rb", 0xc3);
        tagMap.put("bdo", 0xc4);
        tagMap.put("wbr", 0xc5);
        tagMap.put("ins", 0xc6);
        tagMap.put("del", 0xc7);
        tagMap.put("iframe", 0xc8);
        tagMap.put("embed", 0xc9);
        tagMap.put("object", 0xca);
        tagMap.put("param", 0xcb);
        tagMap.put("video", 0xcc);
        tagMap.put("audio", 0xcd);
        tagMap.put("sources", 0xce);
        tagMap.put("canvas", 0xcf);
        tagMap.put("map", 0xd0);
        tagMap.put("area", 0xd1);
        tagMap.put("header", 0xd2);

    }
    public static int fromString(String tag) {
        if (tagMap == null) genTagMap();
        Integer no = tagMap.get(tag);
        if (no == null) return 0;
        return no;
    }
}
//---