#!/usr/bin/env php
<?php
$ini = file_get_contents("KTagNo-gen.ini");

$dbc = [];
$lastno = 0;
$lines = explode("\n", $ini);
$src = "";
$src2 = "";
$src3 = "";
foreach ($lines as $line) {
  $line = trim($line);
  if ($line == "") continue;
  $c = substr($line,0,1);
  if ($c == "#") {
    $src  .= "    // $line\n";
    $src2 .= "        // $line\n";
    $src3 .= "        // $line\n";
    continue;
  }
  //
  list($key, $val) = explode("=", $line."=-1");
  $key = trim($key);
  $val = trim($val);
  $val = intval($val,16);
  if ($val < 0) {
    $val = $lastno+1;
  }
  $lastno = $val;
  if (isset($dbc[$key])) {
    echo "***ERROR double $key ***\n";
    exit;
  }
  //
  $val16 = dechex($val);
  $key2 = strtoupper($key);
  $key2 = str_replace(":", "_", $key2);
  $key2 = str_replace("-", "__", $key2);
  $src  .= "    final public static int $key2 = 0x$val16;\n";
  $src2 .= "        case 0x$val16 : return \"$key\";\n";
  $src3 .= "        tagMap.put(\"$key\", 0x$val16);\n";  
  echo "-$key=$val\n";
}

$header = <<<EOS
// auto generated by KTagNo-gen.php
package com.kujirahand.KPage;
import java.util.HashMap;
/**
 * define tag no
 */
public class KTagNo {
//---
EOS;

$footer = <<<EOS
}
//---
EOS;

$func = <<<EOS
    public static String toString(int no) {
        switch(no) {
{$src2}
        }
        return "unknown";
    }
    private static HashMap<String,Integer> tagMap = null;
    private static void genTagMap() {
        tagMap = new HashMap<String,Integer>();
{$src3}
    }
    public static int fromString(String tag) {
        if (tagMap == null) genTagMap();
        Integer no = tagMap.get(tag);
        if (no == null) return 0;
        return no;
    }
EOS;

$body = <<< EOS
$header
$src
$func
$footer
EOS;

file_put_contents("KTagNo.java", $body);
echo "ok\n";


